### ISSUE TITLE
versions is not a valid array

### ISSUE THREAD

**Issue by thib3113** [flipperdevices/flipper-update-server#3]
Hello,

It seems sometimes, the "versions" array is not an array but `null` .
```
{
            "id": "development",
            "title": "Development Channel",
            "description": "Latest builds, not yet tested by Flipper QA, be careful",
            "versions": null
}
```
( same behavior if I run the project in local without artifacts ) .

It totally breaks the qflipper app if one of the channel return null instead of an empty array (not tested if it works with an empty array) . 

Is it maybe better to return an empty array in versions, instead of null

**Comment by anna-oake** [comment]
Known issue. Fix is in progress.
